"""Alter user password

Revision ID: 6ec395596333
Revises: 84635bbe3143
Create Date: 2025-03-19 09:07:13.980699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec395596333'
down_revision: Union[str, None] = '84635bbe3143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_column('User', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('User', 'hashed_password')
    # ### end Alembic commands ###
